### ISSUE TITLE
由于API关闭导致的发送失败，与音游一言显示连接远程主机被拒

### ISSUE THREAD

**Issue by kyokusanaki** [Pr0pHesyer/RandomDingzhen#1]
一直显示发送失败，还有那个音游一言插件，显示连接远程主机被拒

**Comment by Pr0pHesyer** [comment]
> 一直显示发送失败，还有那个音游一言插件，显示连接远程主机被拒

该插件所使用的API服务器已经寄了，原因嘛…嗯…，毕竟人家是丁真。

音游一言插件的话，可否看看HoshinoBot的log？因为我这里没问题

**Comment by Pr0pHesyer** [comment]
> 一直显示发送失败，还有那个音游一言插件，显示连接远程主机被拒

已更换API，测试可用

**Comment by thankU-ubi** [comment]
还是显示发送失败 ，但是直接访问API可以正常显示图片

**Comment by Pr0pHesyer** [comment]
> 还是显示发送失败 ，但是直接访问API可以正常显示图片

更新模块后请重启bot，若仍有问题请发日志
